Repository Goorm-Lucky7/Dart_BE, pull requests merged in 2024-06, with the labels that each got.

#42 feat: 갤러리 생성과 삭제 시 유저 추가
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/gallery/ImageService.java
  src/main/java/com/dart/api/application/member/MemberController.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/global/common/util/S3Service.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/main/java/com/dart/presentation/GalleryController.java
Labels: 🚀 BE, 🌟 Feature

#48 deploy: CI & CD 파이프라인 수정
  .github/workflows/build-deploy.yml
Labels: 🚀 BE, 🛰️ Deploy

#50 deploy: workflows 파일 분리
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
Labels: 🚀 BE, 🛰️ Deploy

#54 feat: 결제 서비스 회원 추가
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/payment/entity/Payment.java
  src/main/java/com/dart/api/domain/review/entity/Review.java
  src/main/java/com/dart/api/presentation/PaymentController.java
  src/main/java/com/dart/global/common/PaymentConstant.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🌟 Feature

#51 feat: 전체 조회 틀 구현
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/repo/GalleryRepository.java
  src/main/java/com/dart/api/domain/gallery/repo/HashtagRepository.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryAllResDto.java
  src/main/java/com/dart/api/dto/gallery/response/PageGalleryAllRes.java
  src/main/java/com/dart/api/dto/gallery/response/PageInfo.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🌟 Feature

#62 chore: env -> applicatoin secret.yml 변경
  .gitignore
  build.gradle
  src/main/java/com/dart/DartApplication.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/global/config/DotenvEnvironmentLoader.java
  src/main/java/com/dart/global/config/PaymentProperties.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🚀 BE, ⚙️ Setting

#56 feat: 웹소켓 & STOMP 관련 설정 클래스 적용
  build.gradle
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/chat/entity/ChatRoom.java
  src/main/java/com/dart/api/domain/chat/repo/ChatMessageRepository.java
  src/main/java/com/dart/api/domain/chat/repo/ChatRoomRepository.java
  src/main/java/com/dart/api/domain/chat/repo/ChatroomRepository.java
  src/main/java/com/dart/api/domain/chat/repo/MessageRepository.java
  src/main/java/com/dart/api/dto/chat/response/MemberSessionDto.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/MemberSessionRegistry.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/main/resources/static/application-secret.yml
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/support/GalleryFixture.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, 🌟 Feature

#68 deploy: 깃허브 액션 파일 수정
  .dockerignore
  .github/workflows/build-deploy.yml
  .github/workflows/pull-request-build.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  init.sql
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
Labels: 🚀 BE, 🛰️ Deploy

#71 refactor: 불필요한 의존성 제거
  src/main/java/com/dart/api/application/chat/ChatService.java
Labels: 🚀 BE, 🛰️ Deploy

#73 deploy: CI & CD 파이프라인 구축
  Dockerfile
  docker-compose.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/support/MemberFixture.java
  wait-for-it.sh
Labels: 🚀 BE, 🛰️ Deploy

#75 deploy: 배포 파일 수정
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: 🚀 BE, 🛰️ Deploy

#66 refactor: 리뷰엔티티 연관관계 수정
  .github/workflows/pull-request-build.yml
  src/main/java/com/dart/api/application/review/ReviewService.java
  src/main/java/com/dart/api/domain/review/entity/Review.java
  src/main/java/com/dart/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, ⛏️ Refactor

#77 feat: 프로필 이미지 업로드
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/member/entity/Member.java
  src/main/java/com/dart/api/dto/member/request/MemberUpdateDto.java
  src/main/java/com/dart/api/dto/member/response/MemberProfileResDto.java
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🌟 Feature

#81 feat: 이메일 및 닉네임 중복 확인
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/dto/member/request/SignUpDto.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#85 feat: 실시간 채팅 메시지 전송 기능 구현
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, 🌟 Feature

#87 deploy: Dockerfile & Docker Compose 파일을 통해 배포
  .dockerignore
  .github/workflows/build-deploy.yml
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  init.sql
  src/main/resources/application-dev.yml
  wait-for-it.sh
Labels: 🚀 BE, 🛰️ Deploy

#94 미결제 전시관 자동삭제를 구현
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryRepository.java
  src/main/java/com/dart/global/common/util/PaymentConstant.java
  src/main/java/com/dart/global/config/RedisConfig.java
  src/main/java/com/dart/global/config/RedisKeyExpirationListener.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#88 feat: 갤러리 전체 조회 시 필터 구현
  build.gradle
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/entity/Category.java
  src/main/java/com/dart/api/domain/gallery/entity/Cost.java
  src/main/java/com/dart/api/domain/gallery/entity/Display.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/gallery/entity/Sort.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryCustomRepository.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryCustomRepositoryImpl.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryRepository.java
  src/main/java/com/dart/api/domain/gallery/repository/GallerySorter.java
  src/main/java/com/dart/api/domain/gallery/repository/GallerySpecification.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/dto/gallery/response/PageGalleryAllRes.java
  src/main/java/com/dart/api/dto/gallery/response/PageInfo.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
  src/main/java/com/dart/global/config/QuerydslConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#93 fix: 닉네임 중복확인 에러 수정
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#107 feat: 결제 검증 추가
  src/main/generated/com/dart/api/domain/chat/entity/QChatMessage.java
  src/main/generated/com/dart/api/domain/chat/entity/QChatRoom.java
  src/main/generated/com/dart/api/domain/gallery/entity/QGallery.java
  src/main/generated/com/dart/api/domain/gallery/entity/QHashtag.java
  src/main/generated/com/dart/api/domain/gallery/entity/QImage.java
  src/main/generated/com/dart/api/domain/member/entity/QMember.java
  src/main/generated/com/dart/api/domain/member/entity/QVisitor.java
  src/main/generated/com/dart/api/domain/payment/entity/QPayment.java
  src/main/generated/com/dart/api/domain/review/entity/QReview.java
  src/main/generated/com/dart/global/common/entity/QBaseTimeEntity.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/payment/entity/Order.java
  src/main/java/com/dart/api/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryReadIdDto.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/common/util/PaymentConstant.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#106 feat: 갤러리 정보 조회 구현
  src/main/generated/com/dart/api/domain/chat/entity/QChatMessage.java
  src/main/generated/com/dart/api/domain/chat/entity/QChatRoom.java
  src/main/generated/com/dart/api/domain/gallery/entity/QGallery.java
  src/main/generated/com/dart/api/domain/gallery/entity/QHashtag.java
  src/main/generated/com/dart/api/domain/gallery/entity/QImage.java
  src/main/generated/com/dart/api/domain/member/entity/QMember.java
  src/main/generated/com/dart/api/domain/member/entity/QVisitor.java
  src/main/generated/com/dart/api/domain/payment/entity/QPayment.java
  src/main/generated/com/dart/api/domain/review/entity/QReview.java
  src/main/generated/com/dart/global/common/entity/QBaseTimeEntity.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryRepository.java
  src/main/java/com/dart/api/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dart/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/dart/api/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/dart/api/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryInfoDto.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🌟 Feature

#113 fix: Querydsl 의존성 수정 및 and 테스트 코드 주석 처리
  build.gradle
  src/main/generated/com/dart/api/domain/chat/entity/QChatMessage.java
  src/main/generated/com/dart/api/domain/chat/entity/QChatRoom.java
  src/main/generated/com/dart/api/domain/gallery/entity/QGallery.java
  src/main/generated/com/dart/api/domain/gallery/entity/QHashtag.java
  src/main/generated/com/dart/api/domain/gallery/entity/QImage.java
  src/main/generated/com/dart/api/domain/member/entity/QMember.java
  src/main/generated/com/dart/api/domain/member/entity/QVisitor.java
  src/main/generated/com/dart/api/domain/payment/entity/QPayment.java
  src/main/generated/com/dart/api/domain/review/entity/QReview.java
  src/main/generated/com/dart/global/common/entity/QBaseTimeEntity.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/support/GalleryFixture.java
Labels: 🚀 BE, 🐞 Bug & Fix

#100 fix: 사용자 정보 수정 기능 변경
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/member/entity/Member.java
  src/main/java/com/dart/api/dto/member/request/MemberUpdateDto.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#102 feat: refresh token 발급
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/dto/auth/TokenReqDto.java
  src/main/java/com/dart/api/dto/auth/TokenResDto.java
  src/main/java/com/dart/api/dto/member/response/LoginResDto.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/common/util/AuthConstant.java
Labels: 🚀 BE, 🌟 Feature

#104 feat: 사용자 정보 조회 기능 수정
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/member/repository/MemberRepository.java
  src/main/java/com/dart/api/dto/member/response/MemberProfileResDto.java
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🌟 Feature

#114 feat: 채팅방 내 로그인된 사용자 정보 조회 로직 구현
  build.gradle
  src/main/generated/com/dart/api/domain/chat/entity/QChatMessage.java
  src/main/generated/com/dart/api/domain/chat/entity/QChatRoom.java
  src/main/generated/com/dart/api/domain/gallery/entity/QGallery.java
  src/main/generated/com/dart/api/domain/gallery/entity/QHashtag.java
  src/main/generated/com/dart/api/domain/gallery/entity/QImage.java
  src/main/generated/com/dart/api/domain/member/entity/QMember.java
  src/main/generated/com/dart/api/domain/member/entity/QVisitor.java
  src/main/generated/com/dart/api/domain/payment/entity/QPayment.java
  src/main/generated/com/dart/api/domain/review/entity/QReview.java
  src/main/generated/com/dart/global/common/entity/QBaseTimeEntity.java
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptorTest.java
  src/test/java/com/dart/api/infrastructure/websocket/MemberSessionRegistryTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
Labels: 🚀 BE, 🌟 Feature

#117 deploy: GitHub Actions 파일 분리
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
  src/main/resources/application-dev.yml
Labels: 🚀 BE, 🛰️ Deploy

#119 refactor: 결제 페이지 수정
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
  src/main/java/com/dart/global/common/util/PaymentConstant.java
Labels: 🚀 BE, ⛏️ Refactor, 🛰️ Deploy

#121 refactor: CORS 설정 수정
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/global/config/WebConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#122 fix: 로그인 및 토큰 재발급 시 access token을 header와 response body에 담아 전달
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/dto/auth/request/EmailSendReqDto.java
  src/main/java/com/dart/api/dto/auth/request/EmailVerificationReqDto.java
  src/main/java/com/dart/api/dto/auth/response/TokenResDto.java
  src/main/java/com/dart/api/dto/member/response/LoginResDto.java
  src/main/java/com/dart/api/presentation/EmailController.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🚀 BE, 🐞 Bug & Fix

#125 feat: 미결제 전시관 자동삭제 시 채팅방 삭제를 구현
  src/main/java/com/dart/api/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/dart/global/config/RedisKeyExpirationListener.java
  src/main/resources/application-dev.yml
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#126 feat: 갤러리 단건 조회 기능 추가
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/gallery/ImageService.java
  src/main/java/com/dart/api/domain/gallery/repository/ImageRepository.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryResDto.java
  src/main/java/com/dart/api/dto/gallery/response/ImageResDto.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🌟 Feature

#129 refactor: pah variable -> request param 으로 변경
  src/main/java/com/dart/api/domain/member/entity/Member.java
  src/main/java/com/dart/api/dto/member/request/MemberUpdateDto.java
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🐞 Bug & Fix

#133 feat: 리뷰 생성 시 검증 추가
  src/main/java/com/dart/api/application/review/ReviewService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#130 feat: 채팅방 & 채팅메시지 삭제 로직 구현
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptorTest.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
  src/test/java/com/dart/support/ChatFixture.java
Labels: 🚀 BE, 🌟 Feature

#134 refactor: 패키지 구조 변경 및 redis repository 생성
  src/main/java/com/dart/api/application/RedisService.java
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/EmailService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/gallery/ImageService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/infrastructure/redis/RedisConfig.java
  src/main/java/com/dart/api/infrastructure/redis/RedisConstant.java
  src/main/java/com/dart/api/infrastructure/redis/RedisEmailRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisGalleryRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisHashRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisPaymentRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisTokenRepository.java
  src/main/java/com/dart/api/infrastructure/s3/S3Config.java
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/main/java/com/dart/global/common/util/RedisUtil.java
Labels: 🚀 BE, ⛏️ Refactor

#145 refactor: 리다이렉트 변경
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/presentation/PaymentController.java
Labels: 🚀 BE, ⛏️ Refactor

#141 feat: SockJS 설정 추가
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/main/java/com/dart/global/config/WebConfig.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
Labels: 🚀 BE, 🌟 Feature

#146 feat: Kafka를 활용한 웹소켓 기반 실시간 채팅 기능 확장
  build.gradle
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/global/config/WebConfig.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
Labels: 🚀 BE, 🌟 Feature

#143 refactor: 미결제 전시관 자동 삭제 수정
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/infrastructure/redis/RedisGalleryRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisPaymentRepository.java
  src/main/java/com/dart/global/config/RedisKeyExpirationListener.java
Labels: 🚀 BE, ⛏️ Refactor

#148 deploy: 불필요한 중복 GitHub Actions 동작 이슈 해결
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
Labels: 🚀 BE, 🛰️ Deploy

#151 refactor: 리다이렉트 url 변경
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/presentation/PaymentController.java
Labels: 🚀 BE, ⛏️ Refactor

#138 feat: 프로필 조회 기능을 비로그인 사용자도 이용할 수 있도록 수정
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/member/entity/Member.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🌟 Feature

#140 feat: 마이페이지 갤러리 목록 조회 구현
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryRepository.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryMypageResDto.java
  src/main/java/com/dart/api/presentation/MypageController.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#153 refactor: 배포 주소로 리다이렉트 변경
  src/main/java/com/dart/api/presentation/PaymentController.java
  src/main/java/com/dart/global/common/util/PaymentConstant.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#155 feat: 쿠폰관련 엔티티 생성
  src/main/java/com/dart/api/domain/coupon/entity/Coupon.java
  src/main/java/com/dart/api/domain/coupon/entity/CouponType.java
  src/main/java/com/dart/api/domain/coupon/entity/CouponWallet.java
  src/main/java/com/dart/api/domain/coupon/repository/CouponRepository.java
  src/main/java/com/dart/api/domain/coupon/repository/CouponWalletRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyExpirationListener.java
Labels: 🚀 BE, 🌟 Feature

#158 fix: 갤러리 입장 조건 수정
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryInfoDto.java
Labels: 🚀 BE, 🐞 Bug & Fix

#160 feat: 실시간 채팅 데이터 조회 로직 구현을 위한 Redis 설정 추가
  build.gradle
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/dto/chat/response/ChatMessageReadDto.java
  src/main/java/com/dart/api/infrastructure/redis/RedisConstant.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyExpirationListener.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/HashRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/ZSetRedisRepositoryTest.java
  src/test/java/com/dart/global/config/RedisKeyExpirationListenerTest.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
  src/test/java/com/dart/support/ChatFixture.java
Labels: 🚀 BE, 🌟 Feature

#164 refactor: 리다이렉트 URL 변경
  src/main/java/com/dart/global/common/util/PaymentConstant.java
Labels: 🚀 BE, ⛏️ Refactor

#167 refactor: Redis 저장소 클래스의 DDD 기반 리팩토링 및 자료구조별 분리
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/EmailService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/domain/auth/repository/EmailRedisRepository.java
  src/main/java/com/dart/api/domain/auth/repository/TokenRedisRepository.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/domain/payment/repository/PaymentRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/HashRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisHashRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyExpirationListener.java
  src/main/java/com/dart/api/infrastructure/redis/RedisPaymentRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ValueRedisRepository.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/main/java/com/dart/global/config/RedisConfig.java
  src/main/java/com/dart/global/config/S3Config.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/HashRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/ValueRedisRepositoryTest.java
  src/test/java/com/dart/global/config/RedisKeyExpirationListenerTest.java
Labels: 🚀 BE, ⛏️ Refactor

#165 fix: 이미지 업로드 시 파일 크기 제한 제거
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🚀 BE, 🐞 Bug & Fix

#169 deploy: GitHub Actions 배포 시 데아터베이스 초기화 및 중복 실행 이슈 해결
  .github/workflows/pull-request-build.yml
  docker-compose.yml
Labels: 🚀 BE, 🛰️ Deploy

#177 deploy: 데이터베이스 시간 설정 추가
  docker-compose.yml
Labels: 🚀 BE, 🛰️ Deploy

#179 deploy: Nginx 웹소켓 설정 추가
  nginx/default.conf
Labels: 🚀 BE, 🛰️ Deploy

#172 refactor: 갤러리 관련 코드 리팩토링
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/gallery/HashtagService.java
  src/main/java/com/dart/api/application/gallery/ImageService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryResDto.java
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/test/java/com/dart/support/GalleryFixture.java
Labels: 🚀 BE, ⛏️ Refactor

#181 deploy: 웹소켓 연결 시 액세스 토큰 헤더 전송 설정 추가
  nginx/default.conf
Labels: 🚀 BE, 🛰️ Deploy

#182 fix: 유료 전시회 데이터 삭제를 해결
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/global/common/util/PaymentConstant.java
Labels: 🚀 BE, 🐞 Bug & Fix

#183 refactor: 이메일 및 닉네임 중복확인 리팩토링
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/EmailService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/application/member/NicknameService.java
  src/main/java/com/dart/api/application/member/NicknameValidator.java
  src/main/java/com/dart/api/domain/auth/repository/EmailRedisRepository.java
  src/main/java/com/dart/api/domain/auth/repository/NicknameRedisRepository.java
  src/main/java/com/dart/api/domain/auth/repository/SessionRedisRepository.java
  src/main/java/com/dart/api/domain/member/repository/MemberRepository.java
  src/main/java/com/dart/api/dto/member/request/MemberUpdateDto.java
  src/main/java/com/dart/api/dto/member/request/NicknameDuplicationCheckDto.java
  src/main/java/com/dart/api/dto/member/request/SignUpDto.java
  src/main/java/com/dart/api/infrastructure/redis/HashRedisRepository.java
  src/main/java/com/dart/api/presentation/EmailController.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/common/util/AuthConstant.java
  src/main/java/com/dart/global/common/util/CookieUtil.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/main/java/com/dart/global/error/exception/InvalidVerificationCodeException.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, ⛏️ Refactor

#187 refactor: 무/유료 전시회 여부에 따른 채팅 메시지 만료 시간 결정 로직 수정
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/support/GalleryFixture.java
Labels: 🚀 BE, ⛏️ Refactor

#189 feat: 채팅 메시지 전송 시 일반 사용자와 작가를 구분하는 로직 구현
  src/main/java/com/dart/api/application/chat/ChatService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/domain/member/entity/Visitor.java
  src/main/java/com/dart/api/domain/member/repository/VisitorRepository.java
  src/main/java/com/dart/api/dto/chat/response/ChatMessageReadDto.java
  src/test/java/com/dart/api/application/chat/ChatServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/support/GalleryFixture.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, 🌟 Feature

#191 deploy: Docker-Compose MySQL을 AWS RDS로 전환
  docker-compose.yml
  src/main/resources/application-dev.yml
Labels: 🚀 BE, 🛰️ Deploy

#193 deploy: Nginx 서비스 설정 파일 수정
  docker-compose.yml
Labels: 🚀 BE, 🛰️ Deploy

#195 refactor: 만료 메시지 TTL 설정 및 MySQL 저장 로직 구현
  src/main/java/com/dart/api/application/chat/ChatMessageArchiveService.java
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/application/chat/ChatRoomService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyExpirationListener.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/test/java/com/dart/api/application/chat/ChatMessageArchiveServiceTest.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/application/chat/ChatRoomServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/ZSetRedisRepositoryTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/global/config/RedisKeyExpirationListenerTest.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
  src/test/java/com/dart/support/ChatFixture.java
Labels: 🚀 BE, ⛏️ Refactor

#197 feat: 실시간 쿠폰 대기열에 등록 & 발행을 구현
  src/main/java/com/dart/DartApplication.java
  src/main/java/com/dart/api/application/coupon/CouponManageService.java
  src/main/java/com/dart/api/domain/coupon/entity/Coupon.java
  src/main/java/com/dart/api/domain/coupon/entity/CouponWallet.java
  src/main/java/com/dart/api/domain/coupon/repository/CouponRedisRepository.java
  src/main/java/com/dart/api/domain/coupon/repository/CouponRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ValueRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/CouponController.java
  src/main/java/com/dart/global/common/util/CouponConstant.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/api/application/coupon/CouponManageServiceTest.java
  src/test/java/com/dart/support/CouponFixture.java
Labels: 🚀 BE, 🌟 Feature

#202 refactor: 웹소켓 연결 시 인터셉터 비활성화
  nginx/default.conf
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#204 refactor: 웹소켓 SockJS 설정 추가
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
  src/test/java/com/dart/integration/WebSocketConnectionTest.java
Labels: 🚀 BE, ⛏️ Refactor

#208 refactor: 웹소켓 인터셉터 설정 추가
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
  src/test/java/com/dart/integration/WebSocketConnectionTest.java
Labels: 🚀 BE, ⛏️ Refactor

#210 refactor: 웹소켓 인터셉터에서 URL 쿼리 파라미터로부터 토큰 추출
  src/main/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptor.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptorTest.java
Labels: 🚀 BE, ⛏️ Refactor

#212 refactor: 웹소켓 연결 시 액세스 토큰 전달 로직 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptor.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthHandshakeInterceptorTest.java
  src/test/java/com/dart/global/config/WebSocketConfigTest.java
Labels: 🚀 BE, ⛏️ Refactor

#214 refactor: 기존 헤더 전달 방식에서 쿼리 파라미터 방식으로 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
Labels: 🚀 BE, ⛏️ Refactor

#200 fix: 이메일 인증코드 오인식 문제 해결
  src/main/java/com/dart/api/application/auth/EmailService.java
  src/main/java/com/dart/api/dto/auth/request/EmailVerificationReqDto.java
  src/main/java/com/dart/global/common/util/CookieUtil.java
Labels: 🚀 BE, 🐞 Bug & Fix

#217 refactor: 조회 시 cloudfront사용하도록 수정
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🚀 BE, ⛏️ Refactor

#220 refactor: 갤러리 전체 조회 시 hashtags 삭제
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryAllResDto.java
Labels: 🚀 BE, ⛏️ Refactor

#224 feat: 채팅메시지 저장 시 Redis에서 만료된 채팅 메시지를 DB에 저장하는 로직 구현
  src/main/java/com/dart/api/application/chat/ChatMessageArchiveService.java
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ListRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyExpirationListener.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/test/java/com/dart/api/application/chat/ChatMessageArchiveServiceTest.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/ListRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/ZSetRedisRepositoryTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/global/config/RedisKeyExpirationListenerTest.java
Labels: 🚀 BE, 🌟 Feature

#227 refactor: 웹소켓 에러 핸들러 구현 및 인터셉터 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandler.java
  src/main/java/com/dart/global/config/WebSocketConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#221 feat: HTTP와 HTTPS 모두에서 동작하도록 쿠키 설정 변경
  src/main/java/com/dart/global/common/util/CookieUtil.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
Labels: 🚀 BE, ⛏️ Refactor

#229 feat: login api 응답시 사용자 정보 포함하도록 함
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/dto/member/response/LoginResDto.java
Labels: 🚀 BE, ⛏️ Refactor

#223 feat: 갤러리 관련 template 추가
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/gallery/entity/Template.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryResDto.java
  src/main/java/com/dart/global/common/util/CookieUtil.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#232 fix: 유료 갤러리 생성 시 전시 생성 비용을 결제할 수 있도록 변수 추가
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/dto/gallery/request/ImageInfoDto.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryResDto.java
Labels: 🚀 BE, 🐞 Bug & Fix

#235 refactor: 무료 전시의 경우 hasTicket이 항상 true가 되도록 수정
  src/main/java/com/dart/api/application/gallery/GalleryService.java
Labels: 🚀 BE, ⛏️ Refactor

#237 fix: 회원정보 수정 기능 오류 수정
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🐞 Bug & Fix

#239 Revert "fix: 회원정보 수정 기능 오류 수정"
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🐞 Bug & Fix

#240 feat: name -> path
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🐞 Bug & Fix

#244 fix: 사용자 프로필 수정 요청 변경 put -> post
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🐞 Bug & Fix

#248 refactor: WebSocket 메시지 전송 시 JWT 인증 처리 테스트
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandlerTest.java
  src/test/java/com/dart/support/GalleryFixture.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#255 feat: 썸네일 이미지 리사이징
  build.gradle
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryResDto.java
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
Labels: 🚀 BE, 🌟 Feature

#258 feat: 클라이언트 서버 간 SSE 연결 및 실시간 쿠폰 발행 알림 로직 구현
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/application/notification/SSENotificationService.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponRepository.java
  src/main/java/com/dart/api/domain/notification/entity/Notification.java
  src/main/java/com/dart/api/domain/notification/entity/NotificationType.java
  src/main/java/com/dart/api/domain/notification/repository/NotificationRepository.java
  src/main/java/com/dart/api/domain/notification/repository/PendingEventsRepository.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/api/dto/notification/response/NotificationReadDto.java
  src/main/java/com/dart/api/presentation/NotificationController.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#261 feat: 내 쿠폰 조회 api를 구현
  src/main/java/com/dart/api/application/coupon/CouponService.java
  src/main/java/com/dart/api/domain/coupon/entity/GeneralCouponWallet.java
  src/main/java/com/dart/api/domain/coupon/entity/PriorityCouponWallet.java
  src/main/java/com/dart/api/domain/coupon/repository/GeneralCouponWalletRepository.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponWalletRepository.java
  src/main/java/com/dart/api/dto/coupon/response/MyCouponDetail.java
  src/main/java/com/dart/api/dto/coupon/response/MyCouponReadAllDto.java
  src/main/java/com/dart/api/presentation/CouponController.java
  src/test/java/com/dart/api/application/coupon/CouponServiceTest.java
  src/test/java/com/dart/support/CouponFixture.java
Labels: 🚀 BE, 🌟 Feature

#265 feat: 재전시 요청 10회 초과 시 알림 이벤트 전송 로직 구현
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/application/notification/ExhibitionNotificationService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/notification/entity/NotificationType.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
Labels: 🚀 BE, 🌟 Feature

#267 refactor: 채팅메시지 목록 조회 시 인증 및 인가 실패 이슈 해결
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
Labels: 🚀 BE, ⛏️ Refactor

#269 refactor: 실시간 채팅 시 채팅메시지 전송했을 경우 바로 화면에 반영되지 않는 이슈 해결
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/presentation/ChatController.java
Labels: 🚀 BE, ⛏️ Refactor

#271 feat: 채팅 메시지 프로필 이미지 URL 추가 및 JSON 응답 처리
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/dto/chat/response/ChatMessageReadDto.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
Labels: 🚀 BE, 🌟 Feature

#273 refactor: 웹소켓 이벤트 리스너 액세스 토큰 검증 로직 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
Labels: 🚀 BE, ⛏️ Refactor

#275 refactor: 웹소켓 이벤트 리스너 및 웹소켓 인터셉터 로직 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
Labels: 🚀 BE, ⛏️ Refactor

#279 refactor: 웹소켓 인터셉터 리팩토링 및 웹소켓 인증 및 인가 우선순위 처리
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/MemberSessionRegistry.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#281 refactor: 웹소켓 경로 시큐리티 설정 클래스에 추가
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#276 feat: 전시 생성 시 이미지 업로드 과정 보이도록 기능 추가
  src/main/java/com/dart/api/application/gallery/GalleryProgressService.java
  src/main/java/com/dart/api/application/gallery/ImageService.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ValueRedisRepository.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
Labels: 🚀 BE, 🌟 Feature

#278 feat: 결제 시 쿠폰 적용을 구현
  src/main/java/com/dart/api/application/payment/KakaoPayService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/domain/coupon/entity/GeneralCouponWallet.java
  src/main/java/com/dart/api/domain/coupon/entity/PriorityCouponWallet.java
  src/main/java/com/dart/api/domain/coupon/repository/GeneralCouponWalletRepository.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponWalletRepository.java
  src/main/java/com/dart/api/domain/payment/entity/Payment.java
  src/main/java/com/dart/api/dto/payment/request/PaymentCreateDto.java
  src/main/java/com/dart/api/dto/payment/response/AmountVo.java
  src/main/java/com/dart/api/dto/payment/response/PaymentApproveDto.java
  src/main/java/com/dart/api/presentation/PaymentController.java
  src/test/java/com/dart/api/application/coupon/PriorityCouponManageServiceTest.java
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#283 feat: 회원 닉네임과 프로필 이미지 변경에 따른 채팅메시지 업데이트 및 코드 리팩토링
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/dto/chat/request/ChatMessageSendDto.java
  src/main/java/com/dart/api/dto/chat/response/MemberSessionDto.java
  src/main/java/com/dart/api/infrastructure/websocket/MemberSessionRegistry.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
  src/test/java/com/dart/api/infrastructure/websocket/MemberSessionRegistryTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/support/ChatFixture.java
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#291 refactor: 내 쿠폰 조회 시전달 데이터 수정
  src/main/java/com/dart/api/domain/coupon/entity/GeneralCouponWallet.java
  src/main/java/com/dart/api/domain/coupon/entity/PriorityCouponWallet.java
Labels: 🚀 BE, ⛏️ Refactor

#289 refactor: 채팅메시지 최신순 정렬 및 실시간 사용자 정보가 조회되지 않는 이슈 해결
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/application/notification/ExhibitionNotificationService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/notification/entity/NotificationType.java
  src/main/java/com/dart/api/dto/chat/response/MemberSessionDto.java
  src/main/java/com/dart/api/infrastructure/websocket/MemberSessionRegistry.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/api/presentation/GalleryController.java
Labels: 🚀 BE, ⛏️ Refactor

#288 refactor: 갤러리 생성 과정 조회 수정
  src/main/java/com/dart/api/application/gallery/GalleryProgressService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/gallery/ImageService.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/api/presentation/ReviewController.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
Labels: 🚀 BE, 🐞 Bug & Fix

#294 refactor: 실시간 접속 사용자 정보가 조회되지 않는 이슈 해결
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/dart/api/dto/chat/response/MemberSessionDto.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
Labels: 🚀 BE, ⛏️ Refactor

#296 refactor: 결제 시 쿠폰 적용을 못하는 이슈를 수정
  src/main/java/com/dart/api/application/payment/KakaoPayService.java
  src/main/java/com/dart/api/domain/coupon/repository/GeneralCouponWalletRepository.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponWalletRepository.java
Labels: 🚀 BE, 🐞 Bug & Fix

#299 refactor: 웹소켓 인증 및 인가 인터셉터 로직 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
Labels: 🚀 BE, ⛏️ Refactor

#301 refactor: 웹소켓 인터셉터 및 이벤트 리스너 로직 수정
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
Labels: 🚀 BE, ⛏️ Refactor

#303 refactor: 웹소켓 인터셉터에서 이루어지는 연결 확인 로그 추가
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
Labels: 🚀 BE, ⛏️ Refactor

#306 refactor: 웹소켓 인터셉터 및 이벤트 리스너 로직 수정
  src/main/java/com/dart/api/dto/chat/response/MemberSessionDto.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/MemberSessionRegistry.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/test/java/com/dart/api/infrastructure/websocket/MemberSessionRegistryTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
Labels: 🚀 BE, ⛏️ Refactor

#304 refactor: 실시간 쿠폰 로직 수정
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/coupon/PriorityCouponManageService.java
  src/main/java/com/dart/api/application/review/ReviewService.java
  src/main/java/com/dart/api/domain/auth/entity/AuthUser.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/CouponController.java
  src/test/java/com/dart/api/application/coupon/PriorityCouponManageServiceTest.java
  src/test/java/com/dart/integration/WebSocketMessageTest.java
  src/test/java/com/dart/support/CouponFixture.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, ⛏️ Refactor

#309 refactor: 웹소켓 인터셉터 수정 및 이벤트 리스너가 동작하지 않는 이슈 해결
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandler.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandlerTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#310 refactor: 실시간 쿠폰 서비스 DB 부하 줄이기 작업
  src/main/java/com/dart/api/application/coupon/CouponService.java
  src/main/java/com/dart/api/application/coupon/PriorityCouponManageService.java
  src/main/java/com/dart/api/domain/coupon/entity/PriorityCouponWallet.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponWalletRepository.java
  src/main/java/com/dart/global/common/util/CouponConstant.java
  src/test/java/com/dart/api/application/coupon/CouponServiceTest.java
  src/test/java/com/dart/api/application/coupon/PriorityCouponManageServiceTest.java
  src/test/java/com/dart/support/CouponFixture.java
Labels: 🚀 BE, ⛏️ Refactor

#313 deploy: SSE 연결을 위한 Nginx 설정 파일 수정 및 JPA 커넥션 풀 설정
  nginx/default.conf
  src/main/resources/application-dev.yml
Labels: 🚀 BE, 🛰️ Deploy

#318 refactor: JPA 커넥션 풀 설정 수정
  src/main/resources/application-dev.yml
Labels: 🚀 BE, ⛏️ Refactor

#320 refactor: application-dev 파일 수정
  src/main/resources/application-dev.yml
Labels: 🚀 BE, ⛏️ Refactor

#311 refactor: 썸네일 이미지 리사이징 로직 수정
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
Labels: 🚀 BE, ⛏️ Refactor

#326 refactor: 실시간 접속 사용자 프로필 이미지 정보 전달
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/dto/chat/response/MemberSessionDto.java
  src/main/java/com/dart/api/infrastructure/websocket/MemberSessionRegistry.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketEventListener.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/test/java/com/dart/api/infrastructure/websocket/MemberSessionRegistryTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/integration/WebSocketMessageTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#321 refactor: 사용자정보수정 메소드 반환값 수정
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/dto/member/response/MemberSimpleProfileResDto.java
Labels: 🚀 BE, ⛏️ Refactor

#323 feat: Spring Security 예외처리 설정 변경
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandler.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/auth/filter/CustomFilter.java
  src/main/java/com/dart/global/auth/handler/AuthUserArgumentResolver.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandlerTest.java
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#324 feat: 검색어 자동완성
  build.gradle
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/gallery/AutocompleteService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/gallery/repository/AutocompleteRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisDataInitializer.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyPatternDeleter.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/AutocompleteController.java
  src/main/java/com/dart/global/common/util/CharacterProcessor.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/main/java/com/dart/global/config/CacheConfig.java
  src/main/java/com/dart/global/config/RedisConfig.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
Labels: 🚀 BE
