Repository Goorm-Lucky7/Dart_BE, pull requests merged in 2024-05, with the labels that each got.

#2 chore: 프로젝트 초기 세팅
  .env
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/luckyseven/ddua/DduaApplication.java
  src/main/java/luckyseven/ddua/api/global/config/DotenvEnvironmentPostProcessor.java
  src/main/resources/META-INF/spring.factories
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/luckyseven/ddua/DduaApplicationTests.java
Labels: 🚀BE, ⚙️Setting

#6 chore: main 브랜치를 develop 브랜치로 병합
  .env
  .github/pull_request_template.md
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/luckyseven/ddua/DduaApplication.java
  src/main/java/luckyseven/ddua/api/global/config/DotenvEnvironmentPostProcessor.java
  src/main/resources/META-INF/spring.factories
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/luckyseven/ddua/DduaApplicationTests.java
Labels: 🚀BE, ⚙️Setting

#8 feat: 도메인 및 레포지토리 생성
  src/main/java/luckyseven/ddua/api/domain/chat/entity/Chatroom.java
  src/main/java/luckyseven/ddua/api/domain/chat/entity/Message.java
  src/main/java/luckyseven/ddua/api/domain/chat/repo/ChatroomRepository.java
  src/main/java/luckyseven/ddua/api/domain/chat/repo/MessageRepository.java
  src/main/java/luckyseven/ddua/api/domain/gallery/entity/Gallery.java
  src/main/java/luckyseven/ddua/api/domain/gallery/entity/Hashtag.java
  src/main/java/luckyseven/ddua/api/domain/gallery/entity/Image.java
  src/main/java/luckyseven/ddua/api/domain/gallery/repo/GalleryRepository.java
  src/main/java/luckyseven/ddua/api/domain/gallery/repo/HashtagRepository.java
  src/main/java/luckyseven/ddua/api/domain/gallery/repo/ImageRepository.java
  src/main/java/luckyseven/ddua/api/domain/member/entity/Member.java
  src/main/java/luckyseven/ddua/api/domain/member/entity/OAuthProvider.java
  src/main/java/luckyseven/ddua/api/domain/member/entity/Visitor.java
  src/main/java/luckyseven/ddua/api/domain/member/repo/MemberRepository.java
  src/main/java/luckyseven/ddua/api/domain/member/repo/VisitorRepository.java
  src/main/java/luckyseven/ddua/api/domain/payment/entity/PaymentInfo.java
  src/main/java/luckyseven/ddua/api/domain/payment/repo/PaymentInfoRepository.java
  src/main/java/luckyseven/ddua/api/domain/review/entity/Review.java
  src/main/java/luckyseven/ddua/api/domain/review/repo/ReviewRepository.java
  src/main/java/luckyseven/ddua/api/global/common/BaseTimeEntity.java
  src/main/java/luckyseven/ddua/api/global/error/exception/DduaException.java
Labels: 🚀BE, ⚙️Setting

#10 fix: gitignore 파일 수정 및 .env, db, tmp, application-dev.yml 무시 설정
  .env
  .gitignore
  src/main/resources/application-dev.yml
Labels: 🚀BE, ✨Fix

#12 chore: main 브랜치로 develop 브랜치 병합
  .env
  .gitignore
  src/main/java/luckyseven/ddua/api/domain/chat/entity/Chatroom.java
  src/main/java/luckyseven/ddua/api/domain/chat/entity/Message.java
  src/main/java/luckyseven/ddua/api/domain/chat/repo/ChatroomRepository.java
  src/main/java/luckyseven/ddua/api/domain/chat/repo/MessageRepository.java
  src/main/java/luckyseven/ddua/api/domain/gallery/entity/Gallery.java
  src/main/java/luckyseven/ddua/api/domain/gallery/entity/Hashtag.java
  src/main/java/luckyseven/ddua/api/domain/gallery/entity/Image.java
  src/main/java/luckyseven/ddua/api/domain/gallery/repo/GalleryRepository.java
  src/main/java/luckyseven/ddua/api/domain/gallery/repo/HashtagRepository.java
  src/main/java/luckyseven/ddua/api/domain/gallery/repo/ImageRepository.java
  src/main/java/luckyseven/ddua/api/domain/member/entity/Member.java
  src/main/java/luckyseven/ddua/api/domain/member/entity/OAuthProvider.java
  src/main/java/luckyseven/ddua/api/domain/member/entity/Visitor.java
  src/main/java/luckyseven/ddua/api/domain/member/repo/MemberRepository.java
  src/main/java/luckyseven/ddua/api/domain/member/repo/VisitorRepository.java
  src/main/java/luckyseven/ddua/api/domain/payment/entity/PaymentInfo.java
  src/main/java/luckyseven/ddua/api/domain/payment/repo/PaymentInfoRepository.java
  src/main/java/luckyseven/ddua/api/domain/review/entity/Review.java
  src/main/java/luckyseven/ddua/api/domain/review/repo/ReviewRepository.java
  src/main/java/luckyseven/ddua/api/global/common/BaseTimeEntity.java
  src/main/java/luckyseven/ddua/api/global/error/exception/BadRequestException.java
  src/main/java/luckyseven/ddua/api/global/error/exception/ConflictException.java
  src/main/java/luckyseven/ddua/api/global/error/exception/DduaException.java
  src/main/java/luckyseven/ddua/api/global/error/exception/ForbiddenException.java
  src/main/java/luckyseven/ddua/api/global/error/exception/NotFoundException.java
  src/main/java/luckyseven/ddua/api/global/error/exception/ServerErrorException.java
  src/main/java/luckyseven/ddua/api/global/error/exception/UnauthorizedException.java
  src/main/java/luckyseven/ddua/api/global/error/handler/GlobalExceptionHandler.java
  src/main/java/luckyseven/ddua/api/global/error/model/ErrorCode.java
  src/main/java/luckyseven/ddua/api/global/error/model/ErrorResponse.java
  src/main/resources/application-dev.yml
Labels: 🚀BE, ⚙️Setting

#18 deploy: CI & CD 파이프라인 구축
  .github/workflows/build-deploy.yml
  appspec.yml
  scripts/deploy.sh
  src/test/java/luckyseven/dart/DartApplicationTests.java
Labels: 🚀 BE, 🛰️ Deploy

#23 feat: Dotenv을 사용한 환경 변수 로드 추가
  src/main/java/luckyseven/dart/DartApplication.java
  src/main/java/luckyseven/dart/global/config/DotenvEnvironmentLoader.java
  src/main/java/luckyseven/dart/global/config/DotenvEnvironmentPostProcessor.java
  src/main/resources/META-INF/spring.factories
Labels: 🚀 BE, ⚙️ Setting

#21 deploy: Docker 배포 프로세스 구현
  .github/workflows/build-deploy.yml
  Dockerfile
  appspec.yml
  scripts/deploy.sh
  src/main/java/luckyseven/dart/DartApplication.java
Labels: 🚀 BE, 🛰️ Deploy

#26 feat: 카카오페이 결제 서비스 구현
  src/main/java/luckyseven/dart/api/application/payment/PaymentService.java
  src/main/java/luckyseven/dart/api/domain/payment/entity/Order.java
  src/main/java/luckyseven/dart/api/domain/payment/entity/Payment.java
  src/main/java/luckyseven/dart/api/domain/payment/repo/PaymentInfoRepository.java
  src/main/java/luckyseven/dart/api/domain/payment/repo/PaymentRepository.java
  src/main/java/luckyseven/dart/dto/payment/request/PaymentCreateDto.java
  src/main/java/luckyseven/dart/dto/payment/response/PaymentApproveDto.java
  src/main/java/luckyseven/dart/dto/payment/response/PaymentReadyDto.java
  src/main/java/luckyseven/dart/global/common/PaymentConstant.java
  src/main/java/luckyseven/dart/global/config/PaymentProperties.java
  src/main/java/luckyseven/dart/global/error/model/ErrorCode.java
  src/main/java/luckyseven/dart/presentation/PaymentController.java
Labels: 🚀 BE, 🌟 Feature

#27 feat: 전시 생성, 삭제 구현
  .gitignore
  build.gradle
  src/main/java/luckyseven/dart/DartApplication.java
  src/main/java/luckyseven/dart/api/application/gallery/GalleryService.java
  src/main/java/luckyseven/dart/api/domain/gallery/entity/Cost.java
  src/main/java/luckyseven/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/luckyseven/dart/api/domain/gallery/entity/Hashtag.java
  src/main/java/luckyseven/dart/api/domain/gallery/entity/Image.java
  src/main/java/luckyseven/dart/api/domain/gallery/repo/GalleryRepository.java
  src/main/java/luckyseven/dart/api/domain/gallery/repo/HashtagRepository.java
  src/main/java/luckyseven/dart/api/domain/gallery/repo/ImageRepository.java
  src/main/java/luckyseven/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/luckyseven/dart/api/dto/gallery/request/DeleteGalleryDto.java
  src/main/java/luckyseven/dart/api/dto/gallery/request/ImageInfoDto.java
  src/main/java/luckyseven/dart/global/common/util/GlobalConstant.java
  src/main/java/luckyseven/dart/global/common/util/S3Service.java
  src/main/java/luckyseven/dart/global/config/S3Config.java
  src/main/java/luckyseven/dart/global/error/model/ErrorCode.java
  src/main/java/luckyseven/dart/presentation/GalleryController.java
  src/main/resources/application.yml
Labels: 🚀 BE, 🌟 Feature
