Repository Goorm-Lucky7/Dart_BE, pull requests merged in 2024-07, with the labels that each got.

#331 fix: redis data initializer 주석처리
  src/main/java/com/dart/api/domain/gallery/repository/AutocompleteRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisDataInitializer.java
Labels: 🚀 BE, 🐞 Bug & Fix

#335 fix: 에러 발생 이전의 정상 브랜치 push
  src/main/java/com/dart/api/domain/auth/repository/EmailRedisRepository.java
Labels: 🚀 BE, 🐞 Bug & Fix

#336 fix: 에러 발생 이전의 정상 브랜치 push
  src/main/java/com/dart/api/presentation/EmailController.java
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🐞 Bug & Fix

#337 fix: 필터 내에 옵션 처리 추가
  src/main/java/com/dart/global/auth/filter/CustomFilter.java
Labels: 🚀 BE, 🐞 Bug & Fix

#341 fix: 정상동작하던 브랜치로 복구
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/auth/filter/CustomFilter.java
  src/main/java/com/dart/global/auth/handler/AuthUserArgumentResolver.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#328 refactor: SSE 연결 및 실시간 쿠폰 발행 알림 시 응답 포맷 수정
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/application/notification/SSENotificationService.java
  src/main/java/com/dart/api/domain/notification/entity/Notification.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/api/dto/notification/response/NotificationReadDto.java
  src/main/java/com/dart/api/presentation/NotificationController.java
Labels: 🚀 BE, ⛏️ Refactor

#343 fix: 정상동작하던 브랜치로 복구
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/gallery/AutocompleteService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/gallery/repository/AutocompleteRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisDataInitializer.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyPatternDeleter.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/AutocompleteController.java
  src/main/java/com/dart/global/common/util/CharacterProcessor.java
  src/main/java/com/dart/global/config/CacheConfig.java
  src/main/java/com/dart/global/error/handler/GlobalExceptionHandler.java
Labels: 🚀 BE, 🐞 Bug & Fix

#344 fix: 정상동작하던 브랜치로 복구
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🐞 Bug & Fix

#345 fix: 정상동작하던 브랜치로 복구
  src/main/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptor.java
  src/main/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandler.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandlerTest.java
Labels: 🚀 BE, 🐞 Bug & Fix

#340 refactor: 케시 설정을 유연하게 변경
  src/main/java/com/dart/api/application/coupon/PriorityCouponCacheService.java
  src/main/java/com/dart/global/config/CacheConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#347 feat: 사용자정보수정 메소드 반환값 변경
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/member/entity/Member.java
  src/main/java/com/dart/api/presentation/MemberController.java
Labels: 🚀 BE, 🌟 Feature

#334 refactor: 전시회 삭제 시 외래 키 제약 조건 오류 해결
  src/main/java/com/dart/api/application/chat/ChatRoomService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatMessageRepository.java
Labels: 🚀 BE, ⛏️ Refactor

#349 feat: 실시간 쿠폰 알림 로직 추가
  src/main/java/com/dart/api/application/coupon/PriorityCouponManageService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/domain/notification/entity/Notification.java
  src/main/java/com/dart/api/domain/notification/entity/NotificationType.java
  src/main/java/com/dart/api/domain/payment/entity/Payment.java
  src/main/java/com/dart/api/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dart/api/dto/notification/response/NotificationReadDto.java
  src/main/java/com/dart/global/common/util/CouponConstant.java
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#352 refacor: 전시 전체 조회 시 종료된 전시는 뒤로 정렬, 워터마크 추가, 이미지 무손실 압축, sse 응답 통일
  build.gradle
  src/main/java/com/dart/api/application/gallery/GalleryProgressService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/gallery/repository/GalleryCustomRepositoryImpl.java
  src/main/java/com/dart/api/domain/gallery/repository/GallerySorter.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/api/dto/gallery/request/CreateGalleryDto.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryInfoDto.java
  src/main/java/com/dart/api/dto/notification/response/NotificationReadDto.java
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
Labels: 🚀 BE, 🌟 Feature, ⛏️ Refactor

#348 refactor: 토큰재발급 리팩토링 및 동일토큰발급 문제 해결
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/auth/repository/TokenRedisRepository.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
  src/test/java/com/dart/integration/WebSocketMessageTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#354 refactor: 클라이언트 측에서 메시지 전송 시 생성일자를 함께 요청할 수 있도록 수정
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponRepository.java
  src/main/java/com/dart/api/dto/chat/request/ChatMessageCreateDto.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/application/chat/ChatRoomServiceTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/support/ChatFixture.java
  src/test/java/com/dart/support/GalleryFixture.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#356 refactor: SSE 연결 시 클라이언트 측 이벤트 리스너에 데이터가 전달되지 않는 이슈 해결
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
Labels: 🚀 BE, ⛏️ Refactor

#360 refactor: 실시간 쿠폰 발행 알림 서비스 로직 테스트 코드 작성 및 불필요한 로직 제거
  src/main/java/com/dart/api/domain/notification/repository/NotificationRepository.java
  src/main/java/com/dart/api/domain/notification/repository/PendingEventsRepository.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/test/java/com/dart/api/application/coupon/CouponServiceTest.java
  src/test/java/com/dart/api/application/coupon/GeneralCouponManageServiceTest.java
  src/test/java/com/dart/api/application/coupon/PriorityCouponManageServiceTest.java
  src/test/java/com/dart/api/application/notification/CouponNotificationServiceTest.java
  src/test/java/com/dart/api/application/notification/SSENotificationServiceTest.java
  src/test/java/com/dart/api/domain/notification/repository/SSESessionRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketEventListenerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/api/presentation/NotificationControllerTest.java
  src/test/java/com/dart/support/AuthFixture.java
  src/test/java/com/dart/support/ChatFixture.java
  src/test/java/com/dart/support/MemberFixture.java
  src/test/java/com/dart/support/NotificationFixture.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#363 fix: 사용자정보조회 메소드 수정
  src/main/java/com/dart/api/application/member/MemberService.java
Labels: 🚀 BE, 🐞 Bug & Fix, 🔥 HOT

#365 remove: 액세스토큰 만료확인코드 제거
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
Labels: 🚀 BE, 🐞 Bug & Fix

#367 refactor: SSE 알림 수신 시 클라이언트 이벤트 리스너 미작동 이슈
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
  src/test/java/com/dart/api/domain/notification/repository/SSESessionRepositoryTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#371 refactor: 썸네일 이미지 리팩토링
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
Labels: 🚀 BE, ⛏️ Refactor

#370 refactor: 결제 로직 분리 & 동시성 이슈를 해결
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/payment/KakaoPayApproveService.java
  src/main/java/com/dart/api/application/payment/KakaoPayReadyService.java
  src/main/java/com/dart/api/application/payment/PaymentService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/payment/entity/Order.java
  src/main/java/com/dart/api/domain/payment/entity/OrderType.java
  src/main/java/com/dart/api/domain/payment/entity/Payment.java
  src/main/java/com/dart/api/domain/payment/repository/OrderRepository.java
  src/main/java/com/dart/api/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dart/api/presentation/PaymentController.java
  src/main/java/com/dart/global/common/util/PaymentConstant.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, ⛏️ Refactor

#373 refactor: CORS 설정 변경
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#375 feat: 예외처리를 위한 Security Config 설정 추가
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/auth/filter/CustomFilter.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🌟 Feature

#378 fix: AuthencationFilter 수정
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
Labels: 🚀 BE, 🐞 Bug & Fix

#380 fix: CORS 재설정
  src/main/java/com/dart/global/auth/filter/CustomFilter.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#382 fix: spring security 설정 복구
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/auth/filter/CustomFilter.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#369 refactor: SSE 연결 및 실시간 쿠폰 발행 알림 서비스 로직 리팩토링
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/application/notification/SSENotificationService.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
Labels: 🚀 BE, ⛏️ Refactor

#386 feat: reissue 수정
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/domain/auth/entity/RefreshToken.java
  src/main/java/com/dart/api/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/dart/api/domain/auth/repository/TokenRedisRepository.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
Labels: 🚀 BE, 🐞 Bug & Fix

#389 feat: reissue 수정
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/application/gallery/AutocompleteService.java
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/gallery/repository/AutocompleteRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisDataInitializer.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyPatternDeleter.java
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/api/presentation/AutocompleteController.java
  src/main/java/com/dart/global/common/util/CharacterProcessor.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, 🐞 Bug & Fix

#384 deploy: JVM 옵션 설정
  Dockerfile
Labels: 🚀 BE, 🛰️ Deploy

#391 test: 리뷰 서비스 테스트를 구현
  src/main/java/com/dart/api/application/coupon/PriorityCouponManageService.java
  src/test/java/com/dart/api/application/review/ReviewServiceTest.java
Labels: 🚀 BE, 🧚🏻‍♂️ Test

#392 fix: reissue 토큰 재사용 문제 해결
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/domain/auth/repository/TokenRedisRepository.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
Labels: 🚀 BE, 🐞 Bug & Fix, 🔥 HOT

#395 fix: 제약조건 위반문제를 해결하기 위한 flush 추가
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
Labels: 🚀 BE, 🐞 Bug & Fix, 🔥 HOT

#398 refactor: 채팅메시지 목록 조회 서비스 분리 및 변경된 사용자 정보가 반영되도록 수정
  src/main/java/com/dart/api/application/chat/ChatMessageReadService.java
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/domain/member/repository/MemberRepository.java
  src/main/java/com/dart/api/presentation/ChatController.java
  src/test/java/com/dart/api/application/chat/ChatMessageReadServiceTest.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/infrastructure/websocket/AuthChannelInterceptorTest.java
  src/test/java/com/dart/api/infrastructure/websocket/WebSocketErrorHandlerTest.java
  src/test/java/com/dart/api/presentation/ChatControllerTest.java
  src/test/java/com/dart/support/MemberFixture.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#401 fix: 재로그인 오류 해결
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/domain/auth/repository/TokenRedisRepository.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
  src/main/java/com/dart/global/common/util/CookieUtil.java
Labels: 🚀 BE, 🐞 Bug & Fix

#404 fix: Authentication Filter 수정
  src/main/java/com/dart/global/auth/filter/AuthenticationFilter.java
Labels: 🚀 BE, 🐞 Bug & Fix

#402 feat: 진행 예정중인 이벤트 예외처리
  src/main/java/com/dart/api/application/coupon/GeneralCouponManageService.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#405 refactor: 갤러리 삭제 수정
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/review/ReviewService.java
  src/main/java/com/dart/api/domain/gallery/repository/GallerySorter.java
  src/main/java/com/dart/api/domain/review/repository/ReviewRepository.java
  src/main/java/com/dart/api/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/dart/global/common/util/ScoreUtil.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, ⛏️ Refactor

#409 feat: 검색어 자동완성 수정
  src/main/java/com/dart/api/infrastructure/redis/ZSetRedisRepository.java
  src/main/java/com/dart/global/common/util/CharacterProcessor.java
Labels: 🚀 BE, 🌟 Feature

#407 feat: 지난 이벤트 알림을 받는 로직 구현
  src/main/java/com/dart/api/application/notification/CouponNotificationService.java
  src/main/java/com/dart/api/application/notification/SSENotificationService.java
  src/main/java/com/dart/api/domain/notification/entity/Notification.java
  src/main/java/com/dart/api/domain/notification/repository/PendingEventsRepository.java
  src/main/java/com/dart/api/domain/notification/repository/SSESessionRepository.java
  src/main/java/com/dart/api/dto/notification/response/NotificationReadDto.java
  src/main/java/com/dart/api/presentation/NotificationController.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
  src/test/java/com/dart/api/application/notification/SSENotificationServiceTest.java
  src/test/java/com/dart/api/domain/notification/repository/PendingEventsRepositoryTest.java
  src/test/java/com/dart/api/presentation/NotificationControllerTest.java
Labels: 🚀 BE, 🌟 Feature

#412 feat: autocomplete 반환하는 dto 추가
  src/main/java/com/dart/api/application/gallery/AutocompleteService.java
  src/main/java/com/dart/api/dto/gallery/response/AutocompleteResDto.java
  src/main/java/com/dart/api/presentation/AutocompleteController.java
Labels: 🚀 BE, 🌟 Feature, 🔥 HOT

#410 refactor: 썸네일 이미지 처리 수정
  build.gradle
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/dto/gallery/response/GalleryAllResDto.java
  src/main/java/com/dart/api/infrastructure/s3/S3Service.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
  src/main/java/com/dart/global/common/util/ImageConstant.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#415 refactor: 사용자 정보 수정, 조회, 검색어 자동완성
  src/main/java/com/dart/api/application/gallery/AutocompleteService.java
  src/main/java/com/dart/api/application/member/MemberService.java
Labels: 🚀 BE, ⛏️ Refactor

#414 feat: 재전시 요청 횟수가 10회 초과 시 작가에게 알림 전송 로직 구현
  src/main/java/com/dart/api/application/gallery/GalleryService.java
  src/main/java/com/dart/api/application/notification/ExhibitionNotificationService.java
  src/main/java/com/dart/api/domain/gallery/entity/Gallery.java
  src/main/java/com/dart/api/domain/notification/entity/NotificationType.java
  src/main/java/com/dart/api/presentation/GalleryController.java
  src/main/java/com/dart/global/common/util/SSEConstant.java
  src/test/java/com/dart/api/application/notification/ExhibitionNotificationServiceTest.java
Labels: 🚀 BE, 🌟 Feature

#417 refactor: Refresh Token을 DB -> Redis로 옮기기
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/JwtProviderService.java
  src/main/java/com/dart/api/domain/auth/entity/RefreshToken.java
  src/main/java/com/dart/api/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/dart/api/domain/auth/repository/TokenRedisRepository.java
  src/main/java/com/dart/global/common/util/AuthConstant.java
Labels: 🚀 BE, ⛏️ Refactor

#418 feat: 소셜 로그인 구현
  src/main/java/com/dart/api/application/auth/CustomOAuth2UserService.java
  src/main/java/com/dart/api/application/auth/OAuthLoginService.java
  src/main/java/com/dart/api/domain/auth/entity/CustomOAuth2User.java
  src/main/java/com/dart/api/domain/member/entity/Member.java
  src/main/java/com/dart/api/domain/member/entity/OAuthProvider.java
  src/main/java/com/dart/api/domain/member/repository/MemberRepository.java
  src/main/java/com/dart/api/dto/auth/request/OAuthProviderUpdateDto.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/dart/global/common/util/CharacterProcessor.java
  src/main/java/com/dart/global/common/util/OAuthConstant.java
  src/main/java/com/dart/global/config/SecurityConfig.java
  src/main/java/com/dart/global/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🚀 BE, 🌟 Feature

#420 refactor: 실시간 채팅 메시지 목록 조회 시 성능 최적화
  src/main/java/com/dart/api/application/chat/ChatMessageReadService.java
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#424 feat: 전시 생성 템플릿 값 추가
  src/main/java/com/dart/api/domain/gallery/entity/Template.java
Labels: 🚀 BE, 🌟 Feature, 🔥 HOT

#426 deploy: KAKAO & GOOGLE 소셜 로그인 Nginx 설정 추가
  nginx/default.conf
Labels: 🚀 BE, 🛰️ Deploy

#428 deploy: Nginx 설정 파일 소셜 로그인 경로 수정
  nginx/default.conf
Labels: 🚀 BE, 🛰️ Deploy

#432 docs: README 수정 및 업데이트
  readme-image/CI&CD-Pipeline.png
  readme-image/service-architecture.png
  readme-image/team-convention.png
Labels: 🚀 BE, 📜 Docs

#439 refactor: 채팅 메시지가 Redis에 정상적으로 저장되지 않는 이슈
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#438 feat: 소셜로그인 api 경로 수정
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🌟 Feature

#442 refactor: redis config 설정 변경
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponRedisRepository.java
  src/main/java/com/dart/global/config/RedisConfig.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#443 fix: 사용자정보 수정시 발생하는 오류 해결
  src/main/java/com/dart/api/application/member/MemberService.java
  src/main/java/com/dart/api/domain/member/entity/Member.java
Labels: 🚀 BE, 🐞 Bug & Fix, 🔥 HOT

#445 feat: 소셜 로그인 기능 수정
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/api/application/auth/CustomOAuth2UserService.java
  src/main/java/com/dart/api/application/auth/OAuthLoginService.java
  src/main/java/com/dart/api/domain/auth/entity/CustomOAuth2User.java
  src/main/java/com/dart/api/domain/auth/repository/SessionRedisRepository.java
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/dart/global/common/util/CookieUtil.java
  src/main/java/com/dart/global/common/util/GlobalConstant.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
Labels: 🚀 BE, ⛏️ Refactor

#447 feat: 소셜로그인 redirect url 변경
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#449 feat: 대기열 큐 만료 시 쿠폰 수 삭제
  src/main/java/com/dart/api/domain/coupon/repository/PriorityCouponRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/RedisKeyExpirationListener.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/test/java/com/dart/global/config/RedisKeyExpirationListenerTest.java
Labels: 🚀 BE, 🌟 Feature

#451 refactor: 소셜 로그인 수정
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationSuccessHandler.java
Labels: 🚀 BE, ⛏️ Refactor

#453 refactor: 소셜 로그인 설정 변경 및 변수 수정
  src/main/java/com/dart/global/auth/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, ⛏️ Refactor

#457 refactor: 이미지 업로드에 대한 sse 값 수정
  src/main/java/com/dart/api/application/gallery/ImageService.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#459 refactor: 소셜로그인 관련 Spring Securiy 설정 변경
  src/main/java/com/dart/global/config/SecurityConfig.java
Labels: 🚀 BE, 🐞 Bug & Fix

#461 fix: member controller 내의 query parameter 명 변경
  src/main/java/com/dart/api/presentation/MemberController.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
Labels: 🚀 BE, ⛏️ Refactor

#458 refactor: 채팅 메시지 스케줄러를 통해 DB 접근 최소화 및 읽기 성능 최적화
  src/main/java/com/dart/api/application/chat/ChatMessageReadService.java
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/api/infrastructure/redis/ListRedisRepository.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/test/java/com/dart/api/application/chat/ChatMessageReadServiceTest.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
  src/test/java/com/dart/api/infrastructure/redis/ListRedisRepositoryTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test

#463 refactor: createdAt 값이 누락되어 ConstraintViolationException이 발생하는 이슈
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#465 refactor: createdAt 필드 값 설정으로 인한 데이터베이스 이슈
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#467 refactor: 채팅메시지 배치 처리 시 createdAt이 정상적으로 저장되도록 로직 수정
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#469 refactor: NULL 값이 할당되는 createdAt 필드를 현재 시간으로 설정하도록 수정
  src/main/java/com/dart/api/domain/chat/entity/ChatMessage.java
Labels: 🚀 BE, ⛏️ Refactor, 🔥 HOT

#472 refactor: REDIS에 채팅 메시지가 중복 저장되는 이슈
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/domain/chat/repository/ChatRedisRepository.java
  src/main/java/com/dart/global/common/util/ChatConstant.java
  src/main/java/com/dart/global/common/util/RedisConstant.java
  src/main/resources/application-dev.yml
  src/test/java/com/dart/api/application/chat/ChatMessageServiceTest.java
  src/test/java/com/dart/api/domain/chat/repository/ChatRedisRepositoryTest.java
Labels: 🚀 BE, ⛏️ Refactor, 🧚🏻‍♂️ Test, 🔥 HOT

#476 refactor: 클라이언트 측에서 전달하는 시간을 DB 및 REDIS에 반영하도록 수정
  src/main/java/com/dart/api/application/chat/ChatMessageService.java
  src/main/java/com/dart/api/dto/chat/request/ChatMessageCreateDto.java
Labels: 🚀 BE, ⛏️ Refactor

#473 refactor: 리프레쉬 토큰 만료 에러코드 수정
  src/main/java/com/dart/api/application/auth/AuthenticationService.java
  src/main/java/com/dart/global/error/model/ErrorCode.java
Labels: 🚀 BE, ⛏️ Refactor

#480 fix: google.redirect.uri 추가
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🚀 BE, 🐞 Bug & Fix

#483 Docs: 리드미 수정
  README.md
Labels: 📜 Docs

#484 docs: 리드미 수정
  README.md
Labels: 🚀 BE, 📜 Docs

#485 deploy: main 브랜치 푸시 시 트리거되도록 깃허브 액션 설정
  .github/workflows/merge-build-deploy.yml
  .github/workflows/pull-request-build.yml
Labels: 🚀 BE, 🛰️ Deploy
